apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "maxscale.fullname" . }}
  labels:
    {{- include "maxscale.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "maxscale.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "maxscale.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "maxscale.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: readwrite
              containerPort: 4006
              protocol: TCP
            - name: readonly
              containerPort: 4008
              protocol: TCP
            - name: REST_API
              containerPort: 8989
              protocol: TCP
          volumeMounts:
            - name: maxscale-conf
              mountPath: /etc/maxscale.cnf.d/my-maxscale.cnf
      volumes:
        - name: maxscale-conf
          configMap:
            name: maxscale-config-file
