apiVersion: v1
kind: Service
metadata:
  name: {{ include "maxscale.fullname" . }}
  labels:
    {{- include "maxscale.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: readwrite
      port: {{ .Values.service.port1 }}
      targetPort: 4006
      protocol: TCP
    - name: readonly
      port: {{ .Values.service.port2 }}
      targetPort: 4008
      protocol: TCP
    - name: REST_API
      port: {{ .Values.service.port3 }}
      targetPort: 8989
      protocol: TCP

  selector:
    {{- include "maxscale.selectorLabels" . | nindent 4 }}
